const api_prefix = "api"; // doesnt have spash at the beginning and the end
const api_url = process.env.VUE_APP_API_URL; // doesnt have splash at the end
export default {
  server_api: process.env.VUE_APP_API_URL,
  auth: {
    LOGIN: `${api_url}/${api_prefix}/login`,
    REGISTER: `${api_url}/${api_prefix}/register`,
    GET_CAPTCHA: `${api_url}/${api_prefix}/get_captcha`,
    SEND_FORGET_PASSWORD_MAIL: `${api_url}/${api_prefix}/reset-password`,
    CHECK_IF_TOKEN_VALID: `${api_url}/${api_prefix}/reset-password`,
    RESET_PASSWORD: `${api_url}/${api_prefix}/reset-password`,
  },

  common: {
    USER_INFO: `${api_url}/${api_prefix}/user`,
    SHOW_USER_BY_ROLE: `${api_url}/${api_prefix}/showuserbyrole/`,
    GET_ATTENDANCES: `${api_url}/${api_prefix}/student/attendances`
  },

  company: {
    ADD_COMPANY: `${api_url}/${api_prefix}/addcompany`,
    GET_STUDENT_RECORD: `${api_url}/${api_prefix}/getstudentRecord`,
    EDIT_COMPANY: `${api_url}/${api_prefix}/editcompany/`,
    SHOW_COMPANY: `${api_url}/${api_prefix}/showcompany`,
    SHOW_ALL_COMPANY: `${api_url}/${api_prefix}/showallcompany`,
    DELETE_COMPANY: `${api_url}/${api_prefix}/delcompany/`,
    GET_USER_OF_COMPANY: `${api_url}/${api_prefix}/userofcompany`,
    ADD_USER_COMPANY: `${api_url}/${api_prefix}/adduser`,
    UPDATE_USER: `${api_url}/${api_prefix}/edituser`,
    ACCEPT_REQUEST: `${api_url}/${api_prefix}/accept_apply_course_request`,
    REJECT_REQUEST: `${api_url}/${api_prefix}/reject_apply_course_request`,
    GET_USER_REQUESTS: `${api_url}/${api_prefix}/get_user_request`,
    GET_COMPANY_INFORMATION: `${api_url}/${api_prefix}/get_company_info`,
    UPDATE_COMPANY_INFORMATION: `${api_url}/${api_prefix}/update_company_info`,
    FORCE_STUDENT_TO_REREGISTER: `${api_url}/${api_prefix}/force_student_to_register`,
	SEARCH_FOR_USERS_COMPANY: `${api_url}/${api_prefix}/search_for_users_company`,
	TEACHER_LIST: `${api_url}/${api_prefix}/get_company_teacher_list`,
    INSTRUCTOR_LIST: `${api_url}/${api_prefix}/get_instructor_list`,
    GROUPS: `${api_url}/${api_prefix}/groups`,
  },

  category: {
    GET_CATEGORIES: `${api_url}/${api_prefix}/categories`,
    ADD_CATEGORY: `${api_url}/${api_prefix}/addcategory`,
    EDIT_CATEGORY: `${api_url}/${api_prefix}/editcategory/`,
    SHOW_CATEGORY: `${api_url}/${api_prefix}/category`,
    DELETE_CATEGORY: `${api_url}/${api_prefix}/delcategory/`
  },

  admin: {
    GET_USER_LIST: `${api_url}/${api_prefix}/admin/get_user_list`,
    ESSAYS: `${api_url}/${api_prefix}/admin/essays`,
    ESSAYS_ANSWER: `${api_url}/${api_prefix}/admin/essays/answers`,
    ESSAYS_ANSWER_BY_TEACHER: `${api_url}/${api_prefix}/admin/essays/answers-by-teacher`,
    GET_STUDENT_LIST: `${api_url}/${api_prefix}/admin/get_student_list`,
    GET_STUDENT_LIST_COMPANY_BASED: `${api_url}/${api_prefix}/admin/get_student_list_company_based`,
    GET_USER_INFO_BY_ID: `${api_url}/${api_prefix}/admin/get_user_info`,
    UPDATE_USER: `${api_url}/${api_prefix}/admin/update_user`,
    ADD_NEW_USER: `${api_url}/${api_prefix}/admin/ad_new_user`,
    SEARCH_FOR_USER: `${api_url}/${api_prefix}/admin/search_for_users`,
    SEARCH_FOR_STUDENTS: `${api_url}/${api_prefix}/admin/search_for_students`,
    SEARCH_FOR_STUDENTS_INSTRUCTOR: `${api_url}/${api_prefix}/admin/search_for_students_instructor`,
    GET_DASHBOARD: `${api_url}/${api_prefix}/admin/get_dashboard_informartion`,
    BLOCK_USER_TO_QUIZZES: `${api_url}/${api_prefix}/admin/block_user_to_take_quizzes`,
    ASSIGNED_COMPANY_COURSES: `${api_url}/${api_prefix}/admin/assigned_company_courses`,
    DELETE_COMPANY_COURSE: `${api_url}/${api_prefix}/admin/deleteCompanyCourse`,
  },

  user: {
    UPDATE: `${api_url}/${api_prefix}/user/update`,
    DELETE: `${api_url}/${api_prefix}/deluser/`,
    GET_USER_LIST: `${api_url}/${api_prefix}/showuser`,
    GET_INSTRUCTOR: `${api_url}/${api_prefix}/instructor`,
    ATTENDANCES: `${api_url}/${api_prefix}/attendances`,
    GET_INSTRUCTORS: `${api_url}/${api_prefix}/student-teachers`
  },

  course: {
    GET_BY_INSTRUCTOR: `${api_url}/${api_prefix}/get_all_course_for_quiz`,
    GET_COURSES_BY_COMPANY_ID: `${api_url}/${api_prefix}/getAssignedCompanyCourses`,
    GET_BY_ID: `${api_url}/${api_prefix}/courses`,
    GET_ALL: `${api_url}/${api_prefix}/courses`,
	GET_ASSIEND_COURSE: `${api_url}/${api_prefix}/getAssiendCourse`,
    CREATE: `${api_url}/${api_prefix}/addcourse`,
    UPDATE: `${api_url}/${api_prefix}/editcourse`,
    DELETE: `${api_url}/${api_prefix}/course/delete`,
    DELETE_STUDENT_COURSE: `${api_url}/${api_prefix}/deleteStudentCourse`,
    GET_COURSE_OF_COMPANY: `${api_url}/${api_prefix}/courseofcompany`,
    GET_COURSE_BY_STUDENT: `${api_url}/${api_prefix}/getcoursebystudent`,
    GET_COURSE_BY_INSTRUCTOR: `${api_url}/${api_prefix}/getcoursebyinstructor`,
    ADD_COURSE_TO_STUDENT: `${api_url}/${api_prefix}/assigncoursestudent`,
    ADD_COURSE_TO_COMPANY: `${api_url}/${api_prefix}/assigncoursecompany`,
    DUPLICATE_COURSE: `${api_url}/${api_prefix}/duplicateCourse`,
    SEARCH: `${api_url}/${api_prefix}/searchcourse`,
    APPLY_COURSE: `${api_url}/${api_prefix}/apply_course`,
	UPLOAD_COURSE_AUDIO: `${api_url}/${api_prefix}/upload_course_audio`,
	GET_COURSE_AUDIO: `${api_url}/${api_prefix}/get_course_audio`,
	DELTE_AUDIO: `${api_url}/${api_prefix}/delete_course_audio`,
    ESSAYS: `${api_url}/${api_prefix}/course/essays`,
  },

  lesson: {
    GET_BY_ID: `${api_url}/${api_prefix}/lesson`,
    GET_ALL: `${api_url}/${api_prefix}/lesson`,
    CREATE: `${api_url}/${api_prefix}/addlesson`,
    UPDATE: `${api_url}/${api_prefix}/editlesson/`,
    DELETE: `${api_url}/${api_prefix}/dellesson/`,
    SEARCH: `${api_url}/${api_prefix}/searchcourse`,
    LIST_LESSON_BY_COURSEID: `${api_url}/${api_prefix}/lessonbycourseid`,
    ORDER: `${api_url}/${api_prefix}/orderlesson`,
    GET_ALL_BY_COURSE: `${api_url}/${api_prefix}/get_all_lesson_by_course`,
    SESSIONS: `${api_url}/${api_prefix}/live_lessons`,
  },

  quiz: {
    GET_CREATED: `${api_url}/${api_prefix}/quiz/get_quiz_created`,
    CREATE_QUIZ: `${api_url}/${api_prefix}/quiz/create`,
    GET_BY_ID: `${api_url}/${api_prefix}/quiz/get_by_id`,
    UPDATE_QUIZ: `${api_url}/${api_prefix}/quiz/update`,
    GET_FOR_MANAGE: `${api_url}/${api_prefix}/quiz/get_for_manage`,
    GET_ALL: `${api_url}/${api_prefix}/quiz/get_all`,
    SUBMIT_ANSWER: `${api_url}/${api_prefix}/quiz/submit_answer`,
    DELETE_QUIZ: `${api_url}/${api_prefix}/quiz/delete_quiz`,
    GET_RESULT: `${api_url}/${api_prefix}/get_quiz_result`,
    GET_PART_SCORE: `${api_url}/${api_prefix}/get_quiz_part_score`,
    GET_RESULT_REVIEW: `${api_url}/${api_prefix}/getResultReview`,
    GET_RESULT_BY_STUDENT: `${api_url}/${api_prefix}/get_quiz_result_by_student`,
    SEARCH_FOR_QUIZZES: `${api_url}/${api_prefix}/quiz/search_for_quizzes`,
    TAKE_OR_CONTINUEING_QUIZ: `${api_url}/${api_prefix}/quiz/take_or_continue_quiz`,
    CHECK_IF_QUIZ_ATTEMPT_HAS_COMPLETED: `${api_url}/${api_prefix}/quiz/check_if_quiz_attempt_has_completed`,
    MARK_QUIZ_ATTEMPT_AS_DONE: `${api_url}/${api_prefix}/quiz/mark_quiz_attempt_as_done`,
    GET_QUIZ_ATTEMPTS: `${api_url}/${api_prefix}/quiz/get_quiz_attempts`,
    GET_QUIZ_ATTEMPTS_BY_USER: `${api_url}/${api_prefix}/quiz/get_quiz_attempts_by_user/`,
	QUIZ_BLOCK: `${api_url}/${api_prefix}/quiz/quiz_block`,
	GET_QUIZ_BLOCK: `${api_url}/${api_prefix}/quiz/getQuizBlock`,
	QUIZ_BLOCK_UPDATE: `${api_url}/${api_prefix}/quiz/QuizBlockUpdate`,
	QUIZ_BLOCK_UPDATE_ATTEMPT: `${api_url}/${api_prefix}/quiz/QuizBlockUpdateAttempt`,
	GET_QUIZ_FOR_STUDENT: `${api_url}/${api_prefix}/quiz/getQuizForStudent`,
	GET_EXAM_QUIZ_BY_ID: `${api_url}/${api_prefix}/exam-quiz`,
  },

  question: {
    CREATE: `${api_url}/${api_prefix}/addquestion`,
    CREATE_MULTIPLE_QUESTION: `${api_url}/${api_prefix}/add_multiple_question`,
    GET_ALL: `${api_url}/${api_prefix}/question`,
    GET_BY_ID: `${api_url}/${api_prefix}/question`,
    GET_CHILD_QUESTIONS: `${api_url}/${api_prefix}/get_child_questions/`,
    UPDATE: `${api_url}/${api_prefix}/updatequestion/`,
    UPDATE_QUESTION: `${api_url}/${api_prefix}/updatequestions/`,
    REORDER: `${api_url}/${api_prefix}/reorder`,
    UPDATE_MULTIPLE_QUESTION: `${api_url}/${api_prefix}/update_multiple_question`,
    DELETE: `${api_url}/${api_prefix}/delquestion/`,
    GET_QUEST_OF_QUIZ: `${api_url}/${api_prefix}/question-of-quiz`,
    REVIEW_QUEST_OF_QUIZ: `${api_url}/${api_prefix}/review_quiz_pattern`,
    SUBMIT_ANSWER: `${api_url}/${api_prefix}/quiz/submit_answer`,
    GET_QUESTION_BY_QUIZ_ID: `${api_url}/${api_prefix}/question_api/get_questions`,
    DELETE_BY_ID: `${api_url}/${api_prefix}/question_api/delete_by_id`,
    UPDATE_WITH_AUDIO_FILE: `${api_url}/${api_prefix}/question_api/update_question_with_audio`,
    GET_PREVIOUS_QUESTION: `${api_url}/${api_prefix}/question_api/get_previous_question`,
    GET_ALL_QUESTION_BY_QUIZ_ID_FOR_REVIEW: `${api_url}/${api_prefix}/question_api/get_all_question_for_review`,
	CREATE_NEW: `${api_url}/${api_prefix}/create`,
	NEW_QUESTION: `${api_url}/${api_prefix}/newQuestion`,
	DELETE_NEW: `${api_url}/${api_prefix}/delquestion_new/`,
	GET_SINGLE_SET_PARENT: `${api_url}/${api_prefix}/getSingleSetParent`

  },
  answer: {
    GET_BY_ID: `${api_url}/${api_prefix}/answer/`,
    CREATE: `${api_url}/${api_prefix}/addanswer`,
    GET_BY_QUEST_ID: `${api_url}/${api_prefix}/answerbyquest`,
    CREATE_MULTIPLE_ANSWER: `${api_url}/${api_prefix}/answer_api/create_multiple`,
    CREATE_MULTIPLE_ANSWER_FOR_IMAGE: `${api_url}/${api_prefix}/answer_api/create_multiple_for_image`,
    DELETE_MULTIPLE: `${api_url}/${api_prefix}/answer_api/delete_multiple`,
    DELETE_MULTIPLE_EXCEPT: `${api_url}/${api_prefix}/answer_api/delete_multiple_except`,
    GET_BY_STUDENT: `${api_url}/${api_prefix}/get_answer_by_student`,
    UPDATE_MULTIPLE: `${api_url}/${api_prefix}/answer_api/update_multiple`
  }
};
